### ISSUE TITLE
How do I get the data to replicate the experiment？

### ISSUE THREAD

**Issue by jylee-xidian** [endrikacupaj/PRALINE#1]
No such file or directory: PRALINE/data/final/train/conversations.json'

**Comment by jylee-xidian** [comment]
@endrikacupaj could you give me some suggestions?

**Comment by endrikacupaj** [comment]
Hi Lee, due to size, we haven't uploaded the files with the preprocessed paths and conversations. We plan to do it, I can send you an email with them.

**Comment by jylee-xidian** [comment]
Thanks for your reply, I would be very grateful if you can send me an email with them.
email: ljy18792444110@gmail.com

**Comment by ShangQingLiu** [comment]
@endrikacupaj   I am also interested in your project. Can you also hand me the data? My email is osmallfrogo.hchs@gmail.com

**Comment by SRL94** [comment]
Hi, can I also get the data? My email is sirui.li83@gmail.com
Many thanks!

**Comment by SRL94** [comment]
And Can I know how you generated this file: "{ROOT_PATH}/{args.data_path}/{partition}/{args.pretrained_model}_paths.h5"? Thanks a lot.
