### ISSUE TITLE
Data reuqest to replicate the experiment？

### ISSUE THREAD

**Issue by ShangQingLiu** [endrikacupaj/PRALINE#3]
I am also interested in your project. If you can share the data with me would be perfect I can reproduce this experiment. My email is [osmallfrogo.hchs@gmail.com]. (mailto:osmallfrogo.hchs@gmail.com)

**Comment by endrikacupaj** [comment]
Hi, I sent you an email with the data.

**Comment by himani1812** [comment]
Hi Authors,

Kindly share the data for this repo. I am trying to replicate this experiment. My email id is : iitphimani@gmail.com

Thanks in advance
