### ISSUE TITLE
How do I get the data for the replication experiment？

### ISSUE THREAD

**Issue by therain123** [endrikacupaj/PRALINE#4]
Hi ,
I am  interested in your project. Can you share the relevant data with me？ My email is  shiyuzhang309@gmail.com

Thanks

**Comment by endrikacupaj** [comment]
Hi, I send you the data via email.

**Comment by anikaha** [comment]
Hi, I am also interested in your work. If it possible could you share the data that you use? My email is aniskamilah@gmail.com
Thank you in advance
